### ISSUE TITLE
No error for unknown directive

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#121]
Trealla will run following code without error:

```
:- non_exists_directive(main).

main :- write(foo), nl, halt.
```

**Comment by dram** [comment]
It seems that there is a regression in recent commit. I have add another test in trealla-tests repo.

**Comment by infradig** [comment]
Trealla could do that before? Didn't know!

**Comment by dram** [comment]
Yes, it runs without error on commit https://github.com/trealla-lang/trealla/commit/35e3a049bce2a1c7d69b0cb7e839d348369f3a78

**Comment by infradig** [comment]
It doesn't error of course, because there is no checking. But it doesn't
execute a call to mode/1 like yap and swipl do.

Consider this simplified version:

*  mode(X) :- writeln(X).*
*  :- mode(hello).*

then:

*  yap -l test.pro <http://test.pro> -g halt*
*  hello*

Unfortunately in Trealla directives are being processed too early to
execute them as goals. Something I will have to look into.

**Comment by dram** [comment]
OK, I see.

**Comment by dram** [comment]
Fix confirmed, thanks.
