### ISSUE TITLE
Editing Unicode characters in REPL

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#45]
Currently, editing support for Unicode characters is broken in REPL, e.g.:

1. Paste `A = 一二三` in REPL.
2. Type `Backspace` key, half of `三` will be deleted.
3. Type `.` and `Enter` key, Trealla will crash with segmentation fault.

**Comment by infradig** [comment]
Yes, editing doesn't know about utf8 yet.

**Comment by infradig** [comment]
I've done some work on this in the devel branch. It's not finished so don't
file any issues!


On 13 Dec 2016 2:56 pm, "Xin Wang" <notifications@github.com> wrote:

Currently, editing support for Unicode characters is broken in REPL, e.g.:

   1. Paste A = 一二三 in REPL.
   2. Type Backspace key, half of 三 will be deleted.
   3. Type . and Enter key, Trealla will crash with segmentation fault.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/trealla-lang/trealla/issues/45>, or mute the thread

**Comment by infradig** [comment]
A lot better.

**Comment by dram** [comment]
Cool! :tada: 

I find that step 2 in my previous description is still broken, only half of `三` is deleted. I have tested both in xterm and konsole.
