### ISSUE TITLE
POST method support for http module

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#46]
I found that `post10` and `post11` is not included in `http` module, it would be nice to see them to be included, as `POST` method is used quite heavily in Web sites and also RESTful API.

**Comment by infradig** [comment]
Yes, definitely to do.



On 13 Dec 2016 8:32 pm, "Xin Wang" <notifications@github.com> wrote:

I found that post10 and post11 is not included in http module, it would be
nice to see them to be included, as POST method is used quite heavily in
Web sites and also RESTful API.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/trealla-lang/trealla/issues/46>, or mute the thread

**Comment by infradig** [comment]
Will add at some point soon.

**Comment by dram** [comment]
This issue can be closed now, thanks.
